import type { QueueItem, Task } from './types';

export const mockTasks: Task[] = [
  {
    id: 'task_9bd2_review',
    status: 'review',
    title: '接入低上下文 Review Package',
    summary: 'MiMo 已完成修改，等待你审查风险和测试结果。',
    objective: '在不读取完整 diff 的前提下展示 Review Package、风险标记和按文件升级入口。',
    updatedAt: '10:42',
    round: 2,
    priority: 7,
    riskFlags: ['REVIEW_DATA_UNAVAILABLE', 'ISSUES_REPORTED'],
    changedFiles: [
      {
        path: 'apps/admin-ui/src/App.tsx',
        additions: 214,
        deletions: 18,
        risk: 'ISSUES_REPORTED',
        note: '主审查工作台增加了操作确认区。',
      },
      {
        path: 'apps/admin-ui/src/styles.css',
        additions: 382,
        deletions: 4,
        note: '新增 B+C 融合视觉样式。',
      },
      {
        path: 'apps/admin-ui/src/mockData.ts',
        additions: 96,
        deletions: 0,
        risk: 'REVIEW_DATA_UNAVAILABLE',
        note: '断线降级数据；连接 daemon 后会被真实 API 返回值替换。',
      },
    ],
    diffStat: '+692 / -22 across 3 files',
    testResult: 'passed',
    recommendation: '建议先查看风险文件，再决定回复 MiMo 或合并 Worktree。',
    workspaceLabel: 'mimo-bridge-mcp',
    hasWorktree: true,
    source: 'mock',
  },
  {
    id: 'task_2a10_running',
    status: 'running',
    title: '整理本地守护进程 API 草案',
    summary: '正在生成 health、tasks、queue、token-budget 的适配层设计。',
    objective: '设计同进程 MCP 与管理 API 的边界，不创建第二套任务执行进程。',
    updatedAt: '10:39',
    round: 1,
    priority: 6,
    riskFlags: [],
    changedFiles: [],
    diffStat: '尚未生成 Review Package',
    testResult: 'unknown',
    recommendation: '运行中任务只允许查看摘要或取消。',
    workspaceLabel: 'mimo-bridge-mcp',
    hasWorktree: false,
    source: 'mock',
  },
  {
    id: 'task_67c1_waiting',
    status: 'waiting',
    title: '补充任务表单验收标准',
    summary: 'MiMo 需要你说明验收标准是否必须逐条填写。',
    objective: '完善新建任务表单的字段说明和默认值。',
    updatedAt: '10:28',
    round: 1,
    priority: 5,
    riskFlags: [],
    changedFiles: [
      {
        path: 'docs/UI_DEVELOPMENT.md',
        additions: 8,
        deletions: 2,
        note: '等待用户确认文案。',
      },
    ],
    diffStat: '+8 / -2 across 1 file',
    testResult: 'not_run',
    recommendation: '可以回复 MiMo 继续修改，也可以取消任务。',
    workspaceLabel: 'mimo-bridge-mcp',
    hasWorktree: false,
    source: 'mock',
  },
  {
    id: 'task_432e_failed',
    status: 'failed',
    title: '验证 runner 集成测试',
    summary: '已知挂起测试被误触发，任务失败。',
    objective: '跑完整回归时排除 runner-integration.test.mjs。',
    updatedAt: '09:58',
    round: 1,
    priority: 4,
    riskFlags: ['TASK_FAILED', 'NON_ZERO_EXIT'],
    changedFiles: [],
    diffStat: '无代码修改',
    testResult: 'failed',
    recommendation: '查看失败原因和日志尾部，不要读取完整日志。',
    workspaceLabel: 'mimo-bridge-mcp',
    hasWorktree: false,
    source: 'mock',
  },
  {
    id: 'task_88f0_queued',
    status: 'queued',
    title: '增加 Token 空状态',
    summary: '排队中；等待当前 Runner 完成后启动。',
    objective: '当 Token 统计未接入时展示明确空状态。',
    updatedAt: '09:44',
    round: 0,
    priority: 3,
    riskFlags: [],
    changedFiles: [],
    diffStat: '尚未开始',
    testResult: 'unknown',
    recommendation: '可查看或取消。',
    workspaceLabel: 'mimo-bridge-mcp',
    hasWorktree: false,
    source: 'mock',
  },
  {
    id: 'task_cab1_accepted',
    status: 'accepted',
    title: '完善任务列表状态标签',
    summary: '已验收；仅允许只读查看。',
    objective: '让任务列表能清楚区分 queued/running/review/failed。',
    updatedAt: '昨天',
    round: 3,
    priority: 5,
    riskFlags: [],
    changedFiles: [
      {
        path: 'src/tools/list-tasks.ts',
        additions: 18,
        deletions: 7,
        note: '已完成并验收。',
      },
    ],
    diffStat: '+18 / -7 across 1 file',
    testResult: 'passed',
    recommendation: '只读查看历史结果。',
    workspaceLabel: 'mimo-bridge-mcp',
    hasWorktree: false,
    source: 'mock',
  },
];

export const mockQueue: QueueItem[] = [
  {
    taskId: 'task_2a10_running',
    title: '整理本地守护进程 API 草案',
    status: 'running',
    startedAt: '10:39',
    note: '写任务运行中；后续写任务可以提交并进入串行队列。',
  },
  {
    taskId: 'task_88f0_queued',
    title: '增加 Token 空状态',
    status: 'queued',
    position: 1,
    note: '等待当前 Runner 完成后运行。',
  },
];
